### ISSUE TITLE
Unable to use databroker 0.2.5 version,  how to swith  0.0.2 to 0.2.5 or newer version

### ISSUE THREAD

**Issue by aricwang88** [eclipse-velocitas/vehicle-app-python-template#109]
I checked all the branches, no branch use the newer version databroker.  Chatted with KUKSA team and been told  that this is a really old version, some new APIs not working with it.  
                {
                    "name": "databroker",
                    "image": "ghcr.io/boschglobal/kuksa.val/databroker",
                    "version": "0.0.2"
                },
If i want to use databroker 0.2.5 or main branch databroker, how to do? Thanks!

**Comment by BjoernAtBosch** [comment]
We recommend using version 0.0.2 at the moment.

We are currently looking into that issue and want to upgrade to databroker version 0.3.0 in the next days.

**Comment by dennismeister93** [comment]
Completed with: https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/122 & https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/121
