### ISSUE TITLE
MQTT not work when LEDA don't have dapr, try to use native mode failure

### ISSUE THREAD

**Issue by aricwang88** [eclipse-velocitas/vehicle-app-python-template#110]
Right now, LEDA replace k3s with eclipse-kanto, no dapr installed, I'll ask for deployment json from LEDA team. But, I hope I can use native mode. I try to add ENV "SDV_MIDDLEWARE_TYPE=native", VehicleApp crashed at the start up .
Expected Behavior

MQTT work without dapr middleware.
Current Behavior

{"stream":"stderr","log":" File "\u003cfrozen importlib._bootstrap\u003e", line 1027, in _find_and_load\n","time":"2023-02-10T03:36:41.03053799Z"}
{"stream":"stderr","log":" File "\u003cfrozen importlib._bootstrap\u003e", line 1006, in _find_and_load_unlocked\n","time":"2023-02-10T03:36:41.031138768Z"}
{"stream":"stderr","log":" File "\u003cfrozen importlib._bootstrap\u003e", line 688, in _load_unlocked\n","time":"2023-02-10T03:36:41.031748156Z"}
{"stream":"stderr","log":" File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module\n","time":"2023-02-10T03:36:41.032305434Z"}
{"stream":"stderr","log":" File "sdv/config.py", line 49, in \u003cmodule\u003e\n","time":"2023-02-10T03:36:41.032871212Z"}
{"stream":"stderr","log":" File "sdv/config.py", line 36, in init\n","time":"2023-02-10T03:36:41.033520823Z"}
{"stream":"stderr","log":" File "sdv/config.py", line 41, in __create_middleware\n","time":"2023-02-10T03:36:41.034077897Z"}
{"stream":"stderr","log":" File "sdv/native/middleware.py", line 34, in init\n","time":"2023-02-10T03:36:41.034635434Z"}
{"stream":"stderr","log":" File "sdv/native/mqtt.py", line 47, in init\n","time":"2023-02-10T03:36:41.035318342Z"}
{"stream":"stderr","log":" File "paho/mqtt/client.py", line 914, in connect\n","time":"2023-02-10T03:36:41.03607436Z"}
{"stream":"stderr","log":" File "paho/mqtt/client.py", line 1044, in reconnect\n","time":"2023-02-10T03:36:41.036764656Z"}
{"stream":"stderr","log":" File "paho/mqtt/client.py", line 3685, in _create_socket_connection\n","time":"2023-02-10T03:36:41.037425286Z"}
{"stream":"stderr","log":" File "socket.py", line 845, in create_connection\n","time":"2023-02-10T03:36:41.037986138Z"}
{"stream":"stderr","log":" File "socket.py", line 833, in create_connection\n","time":"2023-02-10T03:36:41.038666397Z"}
{"stream":"stderr","log":"ConnectionRefusedError: [Errno 111] Connection refused\n","time":"2023-02-10T03:36:41.03932549Z"}
Possible Solution
Steps to Reproduce

Deploy on the LEDA main branch.

**Comment by aricwang88** [comment]
Reslved and finally, find a solution:
...
"config": {                
        "env": [                    
           "SDV_MIDDLEWARE_TYPE=native",
           "SDV_MQTT_ADDRESS=mqtt://172.17.0.1:1883",
           "SDV_VEHICLEDATABROKER_ADDRESS=grpc://172.17.0.1:30555",
           "SDV_SEATSERVICE_ADDRESS=grpc://172.17.0.1:30051",      
           "RUST_LOG=info",                                        
           "vehicle_data_broker=info"                              
        ],                                                         
        "cmd": []                                                  
    },                   
...

It's ip issue, I should use LEDA's ip, not just localhost.

**Comment by BjoernAtBosch** [comment]
We will check documentation if description is suffiecient

**Comment by BjoernAtBosch** [comment]
The native mode is not officially supported for Python at the moment and documentation about middleware abstraction is missing. For C++ it is reversed: We currently only support "native", Dapr support is missing.
Once we decided how to proceed with supporting Dapr, documentation will be updated.
