### ISSUE TITLE
User guide for velocitas tool or examples

### ISSUE THREAD

**Issue by aricwang88** [eclipse-velocitas/vehicle-app-python-template#111]
$ velocitas
Lifecycle management of Velocitas Vehicle Applications

VERSION
  velocitas-cli/0.2.1 linux-x64 node-v18.5.0

USAGE
  $ velocitas [COMMAND]

TOPICS
  runtime  Create a new Vehicle App

COMMANDS
  deploy   Deploys your Vehicle App to a runtime
  exec     Executes a script contained in one of your installed components.
  help     Display help for velocitas.
  init     Initializes Velocitas Vehicle App
  package  Prints information about packages
  sync     Syncs Velocitas components into your repo.
  upgrade  Updates Velocitas components.

Q: Only limited help information, any example on how to build, how to create a test environment? How to build a docker image?

**Comment by doosuu** [comment]
Hi @aricwang88 please have a look at https://github.com/eclipse-velocitas/cli/blob/main/README.md - if that is not sufficient, we will release a new update to our docs with this PR https://github.com/eclipse-velocitas/velocitas-docs/pull/76 which you are invited to provide feedback for.

Not particularly sure what you mean by "how to build a docker image" - thats not in scope of the CLI.

**Comment by aricwang88** [comment]
Okay, also found in vscode task's json files. Some URLs resources configurable is welcomed, because in CN, most of them slow to download. I'm going to download these packages to local servers.
