### ISSUE TITLE
have no dapr/bin/daprd file

### ISSUE THREAD

**Issue by justgod3** [eclipse-velocitas/vehicle-app-python-template#138]
when I follow the quickstart, Select Start VehicleApp runtime
get the result:
 fork/exec /home/vscode/.dapr/bin/daprd: no such file or directory,

I don't know where the problem is.

**Comment by kse3hi** [comment]
Hello @justgod3, 

Page, that you trying to acquire, is not visible for you as far as we are not exposing Local MQTT port to outside of the DevContainer.
You can observer the work of Local MQTT by approaching it in left Toolbar by pressing on "small cloud item". Follow the photo instructions:
![image](https://user-images.githubusercontent.com/97447206/233603110-c4bf0aad-c178-4689-ba6d-9dff9a5f588d.png)

**Comment by justgod3** [comment]
thank you ,I will try it.
