### ISSUE TITLE
what trigger on_change function in dog mode example?

### ISSUE THREAD

**Issue by justgod3** [eclipse-velocitas/vehicle-app-python-template#148]
hello,  dear developers.
I'm learning how to use this tool. at first i thought the function which is subscribe_data_points  was trigger by changing data points.but 
I thought i was wrong when i see the log ,could you tell me who trigger the subscribe_data_points functions?

![image](https://github.com/eclipse-velocitas/vehicle-app-python-template/assets/41788824/347f5e70-18dd-48d0-abc7-4540f4ce8f18)

**Comment by BjoernAtBosch** [comment]
Hello justgod3,
sorry, for late reaction but our "inbox" notification seems not to work correctly.

Not 100% sure, what you exactly asking about.
"Subscribing data points" actually means that an app is doing a subscription for being notified in case the content of at least one of the data points being part of the subscription is changing.

The data point subscription in the dog-mode app is defined by the annotation `@subscribe_data_points` in front of the `on_change` function. This is triggered during app start already.

With starting the runtime the component called `feedercan` is changing contents of those data points in the data broker, which in turn notifies the app; in detail this results in calling the `on_change` function with the updated values.

Hope that helps and feel welcome to reply if you've further questions.

**Comment by BjoernAtBosch** [comment]
Closing as question is answered. Please reopen if something needs being clarified.
