### ISSUE TITLE
[Bug] The app's Docker image cannot be build "stand-alone" out of the Dockerfile

### ISSUE THREAD

**Issue by BjoernAtBosch** [eclipse-velocitas/vehicle-app-python-template#162]
The app's Dockerfile contains a copy statement for the vehicle model to make it available in the created container.
This copy statement presumes a build step outside the Dockerfile, which is not (necessarily) done if the image build is just referring to the Dockerfile.

Dockerfiles shall be buildable "stand-alone", i.e. without requiring a devContainer where the container needs to be done.

This bug relates to eclipse-velocitas/vehicle-app-python-sdk#84.

**Comment by doosuu** [comment]
Fixed with #197  with which we are now generating all required files directly inside of the Docker build
