### ISSUE TITLE
Run unit tests and linters: Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by patopat** [eclipse-velocitas/vehicle-app-python-template#164]
Hi,

I cloned the example and there is error during Github actions, the others actions are ok : 
![image](https://github.com/eclipse-velocitas/vehicle-app-python-template/assets/20794916/a4677619-38d3-4f4e-b21a-b6a2888684b8)

Can you help me to resolve this issue ?

Reagrds,
Pat

**Comment by MP91** [comment]
Hey @patopat we also saw this recently and are already investigating the issue.

Interestingly if you just run the workflow again, without changing anything, everything works as expected.

Could you also try to run the workflow again?

**Comment by patopat** [comment]
Hi @MP91 I have ran the workflow again but the issue persist, see https://github.com/patopat/MyFirstVehicleApp

**Comment by MP91** [comment]
In your workflows I see that the CI workflow was successful on the second run. But of course this is still an issue...
