### ISSUE TITLE
[Q]: Template sample app is not working!

### ISSUE THREAD

**Issue by MohammedShokr** [eclipse-velocitas/vehicle-app-python-template#173]
I've been encountering an error when attempting to run the sample app included in the template or any other example. I've attached an image of the error message for reference. Unfortunately, the code is not functioning as intended - it should display the current speed on the terminal and respond to MQTT requests, but it is not doing either.

Interestingly, this code was working perfectly fine just a couple of weeks ago. However, it appears to have stopped functioning properly after some recent commits were made.

![ISSUE#1](https://github.com/eclipse-velocitas/vehicle-app-python-template/assets/63115488/4312d23e-a991-44ba-b672-3a293dbdfeb6)

**Comment by dennismeister93** [comment]
Hi @MohammedShokr, thanks for reaching out to us and happy to see trying out velocitas! :)

Could you give us a little bit more information of how to reproduce and what the steps are you did before reaching that state? We will for sure do our best to support you :)

First step you really could do it just starting with a plain environment -> no running docker containers/dangling images
`docker system prune -a -f --volumes` and just follow the quickstart tutorial to start your application:
As most important what you should have an eye on is on the logs of the runtime you started before running your application:
https://eclipse.dev/velocitas/docs/tutorials/quickstart/quickstart/#how-to-start-the-runtime-services

Kind Regards :)

**Comment by dennismeister93** [comment]
Hi @MohammedShokr i tried to reproduce as you said and i didn't face the issue. Please follow these steps again:

- on your local machine terminal: `docker system prune -a -f --volumes`
- create a repository from the template and clone it to your local machine
- start visual studio code, press F1 -> `> Dev Containers: Rebuild Without Cache and Reopen in Container`
- After Dev Container is running: F1 -> `Tasks: Run Task` -> `Local Runtime - Up`
- After Runtime is ready to use: F5 to start the app
- It sometimes takes some seconds until the data is fed by the feedercan until you see logs in the app

I hope this helps and solves your issue! :)

**Comment by MohammedShokr** [comment]
I have followed all of the steps that you mentioned, but unfortunately, I am still experiencing the same problem. In an effort to resolve the issue, I have attempted to start from scratch on two separate machines and even tried using GitHub Codespaces, but the problem persists. Specifically, what I am doing is:
1- Creating a new repo from the python template.
2- Cloning the repo to my machine.
3- Running docker ```system prune -a -f --volumes``` command.
4- Opening VS code and ```Reopen in Container```
5- Starting ```Local Runtime - UP``` task.
6 - Running the main.py that is located in ```./app/src/main.py```

**Comment by doosuu** [comment]
Hi @MohammedShokr  can you please provide the contents of your `.velocitas.json` so we know the exact versions of the velocitas packages you are using?

**Comment by dennismeister93** [comment]
hi @MohammedShokr , versions inside `.velocitas.json` look fine.

how are you starting/running the app?

**Comment by MohammedShokr** [comment]
Hi @dennismeister93, I start the ```local runtime: UP``` task then I run the ```main.py``` code by pressing F5.
Here's a short video showing all my steps:
https://drive.google.com/file/d/1nRp-fax145fJ43SFXUh0zSrTk-43VUk-/view?usp=sharing

**Comment by MohammedShokr** [comment]
I'm pleased to inform you that the problem has been resolved. It turns out that I was running the app using the play button instead of pressing F5. I was unaware of the difference between the two methods. Thank you for taking the time to assist me, and I apologize for any inconvenience this may have caused.
