### ISSUE TITLE
[Bug]: call pip compile after importing an example

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/vehicle-app-python-template#190]
### Severity

Medium

### What release version, tag or commit-hash did you use?

latest

### Current Behavior

After importing an example from the sdk, the apps requirements are just installed. It might happen that the requirements are incompatible with the ones we already have in the devcontainer.

### Steps to Reproduce

1. import example

### Expected Behavior

requirements are checked for incompatibilities

### Possible Solution

pip compile should be called the change also the requirements.txt in the root of the repo,

afterwards the requirements can be installed.

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by kse3hi** [comment]
Fixed in https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/130
