### ISSUE TITLE
[Q]: Mock Service in DevContainer

### ISSUE THREAD

**Issue by eriksven** [eclipse-velocitas/vehicle-app-python-template#207]
### Question

What do you think about integrating the [Mock Service](https://github.com/eclipse/kuksa.val.services/tree/main/mock_service) from Eclipse Kuksa.val.services natively into the DevContainer from the Eclipse Velocitas Template? This could include the option to configure which mock.py gets mounted into the Mock Service container. 

I see this as a replacement for the feedercan . For me, a well configured Mock Service is more helpful than statically replayed VSS signals coming from the feedercan. In addition, using the Mock Service removes the overhead of converting between CAN and VSS every time the feedercan gets executed while at least in the DevContainer the application only work on VSS level anyway.

This question might be better placed in one of the respective runtime repositories, but I asked it here because it concerns all runtimes.

**Comment by doosuu** [comment]
@eriksven Mock Service is already part of the devenv-runtimes repository. It is started up along with the runtime and starts up with the default mock.py. If you need a custom, well configured mock.py (which we are also aiming to provide, but probably we won't be able to provide a one fits all solution), you can drop a mock.py into your workspace root and upon restart of the runtime, the mock service will mount your custom mock.py instead.

**Comment by kse3hi** [comment]
We will also work to improve documentation on this regards: https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/214
