### ISSUE TITLE
[Bug]: Documentation of Mock Service integration is missing

### ISSUE THREAD

**Issue by kse3hi** [eclipse-velocitas/vehicle-app-python-template#214]
It is unclear to users of our templates how to define an own user specific mock.py, i.e. that it is possible to place a mock.py in root folder of the app repo.

### Severity

Medium

### What release version, tag or commit-hash did you use?

-

### Current Behavior

No Documentation 

### Steps to Reproduce

-

### Expected Behavior

Documentation shall be available

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MP91** [comment]
fixed by https://github.com/eclipse-velocitas/velocitas-docs/pull/114
