### ISSUE TITLE
[Bug]: Add version to user callbacks for latest paho-mqtt 2.0.0 version else tests fail.

### ISSUE THREAD

**Issue by manjukiranhc7** [eclipse-velocitas/vehicle-app-python-template#225]
### Severity

Medium

### What release version, tag or commit-hash did you use?

v0.1.1

### Current Behavior

After recent update of paho-mqtt to 2.0.0, my integration tests are failing when it is trying to connect client to broker. This results in failure of my integration tests with below error.

![image](https://github.com/eclipse-velocitas/vehicle-app-python-template/assets/121442541/47a8b0e5-c159-4ecf-ba8d-88cf76e67448)

In older 1x version of paho-mqtt I am not seeing this issue.

### Steps to Reproduce

1. Update paho-mqtt package to latest 2x version
2. Try running tests which involves create and connect mqtt client.
3. Test fails with above error.

### Expected Behavior

Tests should work irrespective paho-mqtt versions.

### Possible Solution

Need to add version to user callbacks: add mqtt.CallbackAPIVersion.VERSION1 as first argument to [Client()]

Tests work fine after enhancing mqtt_util.py in SDK by adding versions explicitly to callbacks.
![image](https://github.com/eclipse-velocitas/vehicle-app-python-template/assets/121442541/06946f06-5ae6-4a30-a226-144f1df361b5)

This issue was expected and solution was provided by paho-mqtt please refer below link.
https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by daniel-schaubach-beg** [comment]
This is related to:
https://github.com/eclipse-velocitas/vehicle-app-python-sdk/issues/118

**Comment by MP91** [comment]
@manjukiranhc7 
We decided to go with version 1.x of the Paho client for now, since we now this is working and we never had issues with it. I added a constraint in the SDK and update the template to use the new SDK with #226.

**Comment by manjukiranhc7** [comment]
@MP91 Thank you
