### ISSUE TITLE
[Q]: How dose vehicle app connect to databroker in "velocitas_sdk"?

### ISSUE THREAD

**Issue by ley901017** [eclipse-velocitas/vehicle-app-python-template#229]
### Question

I try to walk through the `velocitas_sdk` code to research that how to connect databroker by grpc, but I cannot find the code, could you show where the code which is used to connect databroker is? 
In the other words, why dose the `kuksa_client` connect to databroker by websocket. not grpc? Also I have an other question, when this template can support VSS 4.x? Do you have any plans in the future? Because the latest databroker and kuksa.val have supported VSS 4.x.

Thanks a lot.

**Comment by ley901017** [comment]
Also I have an other question, when this template can support VSS 4.x? Do you have any plans in the future? Because the latest databroker and kuksa.val have supported VSS 4.x.

**Comment by BjoernAtBosch** [comment]
Hi Liu,
the communication to the data broker is handled by the `VehicleDataBrokerClient` in `velocitas_sdk/vdb/client.py`.
The actual way how an app connects to a running data broker instance depends on the used middleware, which is configurable between `native and `Dapr`; Dapr is the default currently.

[Dapr](https://dapr.io/) puts a *sidecar* aside each communication party which is responsible to handle all the connections and communication to all other parties. The app is then always just talking via the sidecar to other parties. Dapr-based components use the *Dapr app id* to determine the network address of other parties. In Python SDK the Dapr-related stuff can be found under `velocitas_sdk/dapr`.

But at the moment we are working to remove Dapr from Velocitas (see #232) and will only support native middleware for time being. Native middleware handling you'll find in `velocitas_sdk/native`. It doesn't offer any automated party discovery at the moment. All required comm party addresses needs being configured via environment variables at the moment, e.g. `SDV_MQTT_ADDRESS` for the address of the mqtt broker.

Support of VSS 4 is also "on the way", but will take some time. There is a ticket for that: https://github.com/eclipse-velocitas/vehicle-model-generator/issues/41 

Hope that helps
Björn

**Comment by BjoernAtBosch** [comment]
Closing this receiving no further inquiry. Please re-open if needed
