### ISSUE TITLE
Use this template button is missing 

### ISSUE THREAD

**Issue by AhmedElkazzaz** [eclipse-velocitas/vehicle-app-python-template#250]
### Severity

Trivial

### What release version, tag or commit-hash did you use?

latest

### Current Behavior

Use this template button is missing 

### Steps to Reproduce

.

### Expected Behavior

.

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by erikbosch** [comment]
Thanks for the report. For me the button is visible. How does the corresponding image look for you when you go to https://github.com/eclipse-velocitas/vehicle-app-python-template and which OS/browser are you using?

![image](https://github.com/user-attachments/assets/31bbe2bf-5094-486b-a37b-a3d9fb8d3905)

**Comment by AhmedElkazzaz** [comment]
Thanks for your reply.
When I wrote this issue you were doing some commits and It was not visible for some hours and then it became visible again.

**Comment by erikbosch** [comment]
Good it was solved, closing this issue
