### ISSUE TITLE
DevContainer cannot be created on Linux

### ISSUE THREAD

**Issue by sophokles73** [eclipse-velocitas/vehicle-app-python-template#39]
When trying to build the DevContainer for the Vehicle App repository, the building of the container image fails on my Linux machine with an error to resolve `host.docker.internal`.

I assume that this is because the [Dockerfile](https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/d2539c715d705b2ef36613b0c639ae343b6e5485/.devcontainer/Dockerfile#L44) falls back to using `host.docker.internal:3128` as the HTTP proxy server if no proxy has been defined explicitly by means of the `DEVCONTAINER_PROXY_HOST` and `DEVCONTAINER_PROXY_PORT` environment variables referred to in the [devcontainer.json](https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/d2539c715d705b2ef36613b0c639ae343b6e5485/.devcontainer/devcontainer.json#L8) file.

**Comment by gkreyssing** [comment]
Thanks for reporting this issue. Kai. We will try to reproduce this issue and come back to you asap. 

Just to understand better the background: You followed the instruction as described in our [documentation](https://eclipse-velocitas.github.io/velocitas-docs/docs/tutorials/quickstart/behind_proxy/) to set up the proxy configurations, didn't you?

**Comment by sophokles73** [comment]
No, I did not. I assumed that the *standard* case was to *not* be trapped behind a proxy and that I would only need to do something special, if I were.

**Comment by MP91** [comment]
Hi @sophokles73 could you please try the branch `bugfix/proxy-issue`?

**Comment by sophokles73** [comment]
Ok, this works now with https://github.com/eclipse-velocitas/vehicle-app-python-template/commit/e143fe51c6c7e22b09bc81454a2a010deb87b00e
