### ISSUE TITLE
pre-commit hooks fail in devcontainer

### ISSUE THREAD

**Issue by sophokles73** [eclipse-velocitas/vehicle-app-python-template#45]
Execution of the pre-commit hooks fails in the devcontainer:

![image](https://user-images.githubusercontent.com/5682135/195047750-8e1a18b0-fd01-4d10-8d7a-4057186793d0.png)

A search on the web found some indication that this is due to Python 3.10 on Debian based distros being incompatible: https://github.com/pre-commit/pre-commit/issues/2299

**Comment by gkreyssing** [comment]
Thanks for point out this issue. We will solve this.

**Comment by sophokles73** [comment]
I was able to solve the issue in my local workspace by making sure that the `python3-virtualenv` and `python3-distutils` packages of the underlying linux distribution are being installed in the dev container's base image and then adjusting the version of *virtualenv* in the *requirements-dev.txt* file to `20.13.*` in order to keep using the version that has been installed using the apt tool during (base) image build time.
