### ISSUE TITLE
Runtime container seems to use different Python version than dev container

### ISSUE THREAD

**Issue by sophokles73** [eclipse-velocitas/vehicle-app-python-template#47]
The dev container seems to use Python 3.10 (installed by the [base image Dockerfile](https://github.com/eclipse-velocitas/devcontainer-base-images/blob/main/Dockerfiles/Python/scripts/install-python.sh)).
However, the base image used in the container image being built for running the app seems to be using Python 3.9 instead (https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/e143fe51c6c7e22b09bc81454a2a010deb87b00e/app/Dockerfile#L18).

Not sure if this poses a problem but I guess for consistency, it would be good to use the same version of Python for both, wouldn't it?

**Comment by MP91** [comment]
@sophokles73  We need at least Python 3.9 to support all the M1 Macs (and other ARM platforms), so it is not a problem I guess but you are right, we should synchronize that.

**Comment by MP91** [comment]
fixed with #46
