### ISSUE TITLE
QL Code failed with the following error in the initital step 

### ISSUE THREAD

**Issue by arsibo** [eclipse-velocitas/vehicle-app-python-template#53]
init post-action step failed: Error: Config file could not be found at expected location. Did the 'init' action fail to start?

**Comment by gkreyssing** [comment]
You need a license for GitHub Advance security and enable it on the setting of your repository.

**Comment by gkreyssing** [comment]
We using the GH Advance security to validate the template themself for security issues. Currently we refactoring the template to use more references instead of code in the template. We will afterwards check if we remove the QL code check from the template repository.

**Comment by mml5bg** [comment]
Resolved in https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/87
