### ISSUE TITLE
Export MQTT_PORT & VDB_PORT by default as environment variables

### ISSUE THREAD

**Issue by DocMoebiuz** [eclipse-velocitas/vehicle-app-python-template#54]
When you deploy K3D and the containerized runtime and apps, for successfully running the integration tests, the ports of MQTT broker and Vehicle Data Broker that are exposed from the cluster, have to be exported as environment variables.

The documentation for this is easy to miss and hard to find when looking for it.

Proposal:
* Export `MQTT_PORT=31883`and `VDB_PORT=30555` automatically, e.g. as part of a task
* Update the documentation accordingly

Acceptance criteria:
* Developer can run integration test of containerized app without having to configure anything additionally/explictly

**Comment by BjoernAtBosch** [comment]
Plan is to deprecate K3D -> will not provide fix
